name: tsundoku
description: A simple flutter app to make a record and save all the data of your physical books into one organized view..
publish_to: 'none'
version: 0.6.6

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  intl: ^0.18.1
  csv: ^5.0.2
  path_provider: ^2.1.0
  file_picker: ^5.3.3
  logger: ^2.0.1
  permission_handler: ^10.4.3
  # books_finder: ^4.4.0
  change_app_package_name: ^1.1.0
  flutter_barcode_scanner: ^2.0.0
  books_finder:
    git:
      url: https://github.com/hilmihisham/books_finder.git
  envied: ^0.5.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
